services:
  producer:
    build: .
    stdin_open: true
    tty: true
    ports:
      - "8585:8585"
    restart: always
    networks:
      - projet-data-pipeline-net
    volumes:
      - ./app:/producer/app
    command: ["python3", "producer.py"]
networks:
  projet-data-pipeline-net:
    external: true
