name: traffic_rennes_producer

services:  
  producer:
    container_name: producer
    build: .
    stdin_open: true
    tty: true
    ports:
      - "8585:8585"
    restart: always
    networks:
      - traffic_rennes_net
    volumes:
      - ./app:/producer/app
    command: ["python3", "producer.py"]
networks:
  traffic_rennes_net:
    external: true
