{
 "title": "New dashboard",
 "time": { "from": "2026-03-14T22:45:00.000Z", "to": "2026-03-16T14:55:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "select hierarchie from traffic_realtime;"
    }
   },
   {
    "name": "street",
    "label": "Street Name",
    "query": {
     "query": "select denomination from traffic_realtime where hierarchie = ${group:sqlstring} allow filtering;"
    }
   }
  ]
 },
 "panels": [
  { "title": "${group}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "group" },
  {
   "title": "Average speed by Group",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "target": "select denomination, avg(avg_speed) as \"Average Speed\", max_speed as \"Maximum Speed\"\nfrom traffic_realtime\nwhere hierarchie = ${group:sqlstring}\ngroup by denomination\nallow filtering;"
    }
   ]
  },
  {
   "title": "Average Time Travel by group",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "select denomination, avg(travel_time) as \"Average Time Travel\"\nfrom traffic_realtime\nwhere hierarchie = ${group:sqlstring}\ngroup by denomination\nallow filtering;"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 13, "x": 11, "y": 23 },
   "targets": [
    {
     "target": "select * from traffic_mapping where hierarchie = ${group:sqlstring} allow filtering;"
    }
   ]
  },
  { "title": "${street}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 }, "repeat": "street" },
  {
   "title": "Map",
   "type": "geomap",
   "gridPos": { "h": 20, "w": 11, "x": 0, "y": 41 },
   "targets": [
    {
     "target": "select * from traffic_mapping\nwhere denomination = ${street:sqlstring} and hierarchie = ${group:sqlstring} and date_time >= $__from and date_time <= $__to\nallow filtering;"
    }
   ]
  },
  {
   "title": "Average speed ",
   "type": "timeseries",
   "description": "The average speed on each segment",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "target": "select denomination, date_time, avg_speed as\"Average Speed\", max_speed from traffic_realtime where denomination = ${street:sqlstring};"
    }
   ]
  },
  {
   "title": "Time Travel",
   "type": "timeseries",
   "description": "The average time it takes to travel through the segment",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "select denomination, date_time, travel_time as \"Travel Time\" from traffic_realtime where denomination = ${street:sqlstring};"
    }
   ]
  }
 ]
}